export const HRLinkApiEndpoints = {
    Award: {
        create: 'Award/Add',
        edit: 'Award/Edit',
        delete: 'Award/Delete',
        search: 'Award/Search',
        getList: 'Award/GetList',
        getDetail: 'Award/Get',
    },
    Course: {
        create: 'Course/Add',
        edit: 'Course/Edit',
        delete: 'Course/Delete',
        search: 'Course/Search',
        getList: 'Course/GetCourseList?TypeId=2',
        getDetail: 'Course/Get',
    },
    Education: {
        create: 'Education/Add',
        edit: 'Education/Edit',
        delete: 'Education/Delete',
        search: 'Education/Search',
        getList: 'Education/GetList',
        getDetail: 'Education/Get',
        universities: 'Education/GetUniversity',
        fields: 'MasterService/GetFieldOfEducation',
    },
    Experience: {
        create: 'Experience/Add',
        edit: 'Experience/Edit',
        delete: 'Experience/Delete',
        search: 'Experience/Search',
        getList: 'Experience/GetList',
        getDetail: 'Experience/GetDetails',
        activityTypes: 'Experience/TypeOfActivity',
        industries: 'MasterService/GetIndustrys',
    },
    Skills: {
        create: 'UserSkill/Add',
        edit: 'UserSkill/Edit',
        delete: 'UserSkill/Delete',
        search: 'UserSkill/Search',
        hardSkills: 'UserSkill/UserSkillProfisionalAndSearch',
        softSkills: 'UserSkill/UserSkillGeneralAndSearch',
        byType: 'UserSkill/GetSkillsByType',
        byParentIdAndType: 'UserSkill/GetSkillsByParentIdAndType',
    },
    Company: {
        list: 'Company/GetCompaniesList',
        sendRequest: 'Company/SendRequest',
        detail: 'Company/GetDetail',
        follow: 'Company/FollowAndUnFollowCompany',
    },
    JobOffers: {
        list: 'JobOffers/GetAndSearchJobOffer',
        opportunities: 'JobOffers/GetAndSearchJobOpportunities',
    },
    Profile: {
        get: 'Profile/GetProfile',
        changePassword: 'profile/ChangePassword',
        edit: 'Profile/EditProfile',
        getGeneralSetting: 'Profile/GetGeneralSetting',
        editGeneralSetting: 'Profile/EditGeneralSetting',
    },
    User: {
        get: 'User/GetUser',
        edit: 'User/Edit',
        addLocation: 'MasterService/AddLocation',
        editLocation: 'MasterService/EditLocation',
        jobGroup: 'MasterService/GetJobGroup',
        jobCategory: 'MasterService/GetJobCategory',
        militaryStatus: 'MasterService/GetMilitaryStatus',
        placeByLevel: 'MasterService/GetPlaceByLevel?level=1',
    },
    Dashboard: {
        data: 'Dashboard/GetAllAdaptionByUserId',
    },
    Auth: {
        logout: 'https://hrlink.hrbox.me:50443/DesktopModules/SSO/api/Login/LogOff',
    },
};
